# Control file for continuous integration testing at http://travis-ci.org/

language: c

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: clang
    - os: linux
      dist: bionic
      compiler: gcc

env:
  global:
    - HTSDIR=./htslib

# For linux systems
addons:
  apt:
    packages:
    - libsodium-dev

before_script:
  # Clone htslib, trying the same branch name in the owners' copy of htslib.
  # If this exists then the user is likely making a joint PR to htslib and
  # samtools and we want to validate this PR works in the context of their
  # htslib.  If not, then we need to test this PR against the upstream
  # develop htslib as this is what we'll be linking against once merged.
  # Logic for choosing which to use is in the .travis/clone script.
  - .travis/clone "git://github.com/$(dirname $TRAVIS_REPO_SLUG)/htslib.git" "$HTSDIR" "$TRAVIS_BRANCH"

script:
  - |
    autoconf && autoheader && \
    ( cd $HTSDIR && \
      autoconf && autoheader && \
      ./configure --enable-plugins && \
      make ) && \
    ( ./configure --with-htslib="$HTSDIR" || \
      ( cat config.log ; /bin/false ) \
    ) && \
    make && \
    make test
